### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by lonix1** [rwasef1830/BundlerMinifier#1]
Just a quick note to say thanks for maintaining this code. And the fact that it's a CLI tool makes it even more useful than before.

I wanted something simple for a RazorPages project. I'm using libman to get the dependencies, and this for bundling/minifying. Is that how you do it? What about scss->css and ts->js?

**Comment by rwasef1830** [comment]
@lonix1 For scss -> css you can use excubo webcompiler (use the preview version that uses dart-sass).

https://github.com/excubo-ag/WebCompiler
for ts -> js I don't know. I haven't needed it yet.

Yes the best thing about this version that it's updated tracking fixes in NUglify completely automatically using GitHub actions (including release on NuGet). So it will be always up-to-date.
