### ISSUE TITLE
NU1202 Package BundlerMinifier.Core.Tool 7.0.3 is not compatible with net6.0/7.0/8.0

### ISSUE THREAD

**Issue by e-tao** [rwasef1830/BundlerMinifier#2]
### Package version
BundlerMinifier.Core.Tool 7.0.3

### Description
I am trying to install BundlerMinifier.Core.Tool via NuGet, and I got this error.

Error	NU1202	Package BundlerMinifier.Core.Tool 7.0.3 is not compatible with net8.0 (.NETCoreApp,Version=v8.0). Package BundlerMinifier.Core.Tool 7.0.3 supports:
  - net6.0 (.NETCoreApp,Version=v6.0) / any
  - net7.0 (.NETCoreApp,Version=v7.0) / any
  - net8.0 (.NETCoreApp,Version=v8.0) / any

I've tried to lower the install version to 7.0 but I still got the same problem.
I also tried to change my project target framework to .net 6.0, .net 7.0 and .net 8.0 all have the same problem, 

I am using Visual Studio 2022 Enterprise.
I am not sure if I missed something.

**Comment by rwasef1830** [comment]
@e-tao do not install this via nuget. This is a dotnet tool, install it using dotnet tool install. The nuget error message is very bad and wrong, and not saying the real reason. This fork is not intended to be referenced from your project, but to be called from csproj, see README. If this is not your case, feel free to reopen.
